=== fmadore/Remoboko/schemas/collaborators.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Collaborator": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S"
      },
      "Gender": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "Affiliation": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S"
      },
      "Country": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S"
      },
      "Coordinate location": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S"
      },
      "URL": {
        "type": "string",
        "format": "uri"
      }
    },
    "required": [
      "Collaborator",
      "Gender",
      "Affiliation",
      "Country",
      "Coordinate location",
      "URL"
    ],
    "additionalProperties": false
  },
  "minItems": 1
}

=== fmadore/Remoboko/Final report/Data/Collaborators_data.json
[
    {
        "Collaborator":"Abdoulbaki Djibo",
        "Gender":"male",
        "Affiliation":"Abdou Moumouni University",
        "Country":"Niger",
        "Coordinate location":"13.50136111,2.09852778",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/abdoulbaki-djibo"
    },
    {
        "Collaborator":"Adedeji Adebayo",
        "Gender":"male",
        "Affiliation":"University of Ibadan",
        "Country":"Nigeria",
        "Coordinate location":"7.4416666666667,3.9",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/adebayo-adedeji"
    },
    {
        "Collaborator":"Adeyemi Balogun",
        "Gender":"male",
        "Affiliation":"Osun State University",
        "Country":"Nigeria",
        "Coordinate location":"7.7616469,4.6012166",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/adeyemi-balogun"
    },
    {
        "Collaborator":"Agn\u00e8s Badou",
        "Gender":"female",
        "Affiliation":"Laboratoire d'Etudes et de Recherche sur les Dynamiques Sociales et le D\u00e9veloppement Local B\u00e9nin",
        "Country":"Benin",
        "Coordinate location":"9.341822504659815,2.592843961135946",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/agnes-badou"
    },
    {
        "Collaborator":"Ahmadou Hamage Issa",
        "Gender":"male",
        "Affiliation":"University of Bayreuth",
        "Country":"Germany",
        "Coordinate location":"49.92885,11.5859",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/ahmadou-hamage-issa"
    },
    {
        "Collaborator":"Amadou Issoufou",
        "Gender":"male",
        "Affiliation":"Abdou Moumouni University",
        "Country":"Niger",
        "Coordinate location":"13.50136111,2.09852778",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/amadou-issoufou"
    },
    {
        "Collaborator":"Amadou Oumarou",
        "Gender":"male",
        "Affiliation":"Abdou Moumouni University",
        "Country":"Niger",
        "Coordinate location":"13.50136111,2.09852778",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/amadou-oumarou"
    },
    {
        "Collaborator":"Amanda tho Seeth",
        "Gender":"female",
        "Affiliation":"German Institute for Global and Area Studies",
        "Country":"Germany",
        "Coordinate location":"53.557222,9.992222",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/amanda-tho-seeth"
    },
    {
        "Collaborator":"Anandita Bajpai",
        "Gender":"female",
        "Affiliation":"Leibniz-Zentrum Moderner Orient",
        "Country":"Germany",
        "Coordinate location":"52.427976,13.202396",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/anandita-bajpai"
    },
    {
        "Collaborator":"Andr\u00e9 Chappatte",
        "Gender":"male",
        "Affiliation":"University of Geneva",
        "Country":"Switzerland",
        "Coordinate location":"46.19899, 6.14446",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/andre-chappatte"
    },
    {
        "Collaborator":"Anna Schenkenberger",
        "Gender":"female",
        "Affiliation":"Leibniz-Zentrum Moderner Orient",
        "Country":"Germany",
        "Coordinate location":"52.427976,13.202396",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/anna-schenkenberger"
    },
    {
        "Collaborator":"Anna Schnieder-Kr\u00fcger",
        "Gender":"female",
        "Affiliation":"Humboldt University of Berlin",
        "Country":"Germany",
        "Coordinate location":"52.518055555556,13.393333333333",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/anna-schnieder-kruger"
    },
    {
        "Collaborator":"Anne Heffernan",
        "Gender":"female",
        "Affiliation":"Durham University",
        "Country":"United Kingdom",
        "Coordinate location":"54.775,-1.575",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/anne-heffernan"
    },
    {
        "Collaborator":"Benjamin Lawrance",
        "Gender":"male",
        "Affiliation":"University of Arizona",
        "Country":"United States of America",
        "Coordinate location":"32.231667, -110.951944",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/benjamin-lawrance"
    },
    {
        "Collaborator":"Benedikt Pontzen",
        "Gender":"male",
        "Affiliation":"Leibniz-Zentrum Moderner Orient",
        "Country":"Germany",
        "Coordinate location":"52.427976,13.202396",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/benedikt-pontzen"
    },
    {
        "Collaborator":"Birgit Meyer",
        "Gender":"female",
        "Affiliation":"Utrecht University",
        "Country":"Netherlands",
        "Coordinate location":"52.085277777777776,5.175",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/birgit-meyer"
    },
    {
        "Collaborator":"Britta Bayer",
        "Gender":"female",
        "Affiliation":"University of Cologne",
        "Country":"Germany",
        "Coordinate location":"50.928055555556,6.9286111111111",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/britta-bayer"
    },
    {
        "Collaborator":"Bruno Reinhardt",
        "Gender":"male",
        "Affiliation":"Universidade Federal de Santa Catarina",
        "Country":"Brazil",
        "Coordinate location":"-27.6011,-48.52",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/bruno-reinhardt"
    },
    {
        "Collaborator":"Chikas Ishaku Tsilpi",
        "Gender":"female",
        "Affiliation":"University of Jos",
        "Country":"Nigeria",
        "Coordinate location":"9.9692,8.884",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/chikas-ishaku-tsilpi"
    },
    {
        "Collaborator":"Cindy Morillas",
        "Gender":"female",
        "Affiliation":"University of Johannesburg",
        "Country":"South Africa",
        "Coordinate location":"-26.183333333333,27.998888888889",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/cindy-morillas"
    },
    {
        "Collaborator":"Daniele Cantini",
        "Gender":"male",
        "Affiliation":"University of Halle-Wittenberg",
        "Country":"Germany",
        "Coordinate location":"51.48638889,11.96888889",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/daniele-cantini"
    },
    {
        "Collaborator":"Danladi Abah",
        "Gender":"male",
        "Affiliation":"Kogi State University",
        "Country":"Nigeria",
        "Coordinate location":"7.480942,7.187462",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/danladi-abah"
    },
    {
        "Collaborator":"Dorothea Schulz",
        "Gender":"female",
        "Affiliation":"University of M\u00fcnster",
        "Country":"Germany",
        "Coordinate location":"51.964,7.613",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/dorothea-schulz"
    },
    {
        "Collaborator":"Dr. Afdawaiza",
        "Gender":"male",
        "Affiliation":"Sunan Kalijaga Islamic University",
        "Country":"Indonesia",
        "Coordinate location":"-7.784758110931052,110.39435184060227",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/dr-afdawaiza"
    },
    {
        "Collaborator":"Duane Jethro",
        "Gender":"male",
        "Affiliation":"Centre for Anthropological Research on Museums and Heritage",
        "Country":"Germany",
        "Coordinate location":"52.51272058842476,13.395041557671924",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/duane-jethro"
    },
    {
        "Collaborator":"Ebenezer Obadare",
        "Gender":"male",
        "Affiliation":"Council on Foreign Relations",
        "Country":"United States of America",
        "Coordinate location":"40.768496836563955, -73.96615065791954",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/ebenezer-obadare"
    },
    {
        "Collaborator":"\u00c9lodie Apard",
        "Gender":"female",
        "Affiliation":"Les Afriques dans le monde",
        "Country":"France",
        "Coordinate location":"44.806666666666665,-0.6311111111111111",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/elodie-apard"
    },
    {
        "Collaborator":"Eva Spies",
        "Gender":"female",
        "Affiliation":"University of Bayreuth",
        "Country":"Germany",
        "Coordinate location":"49.92885,11.5859",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/eva-spies"
    },
    {
        "Collaborator":"Francis Ars\u00e8ne Fogu\u00e9 Kuat\u00e9",
        "Gender":"male",
        "Affiliation":"Universit\u00e9 de Bu\u00e9a",
        "Country":"Cameroon",
        "Coordinate location":"4.14977,9.28774",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/francis-arsene-fogue-kuate"
    },
    {
        "Collaborator":"Gado Alzouma",
        "Gender":"male",
        "Affiliation":"Abdou Moumouni University",
        "Country":"Niger",
        "Coordinate location":"13.50136111,2.09852778",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/gado-alzouma"
    },
    {
        "Collaborator":"Gerd Spittler",
        "Gender":"male",
        "Affiliation":"University of Bayreuth",
        "Country":"Germany",
        "Coordinate location":"49.92885,11.5859",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/gerd-spittler"
    },
    {
        "Collaborator":"Guy Bucumi",
        "Gender":"male",
        "Affiliation":"University of Sherbrooke",
        "Country":"Canada",
        "Coordinate location":"45.379405555556,-71.927661111111",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/guy-bucumi"
    },
    {
        "Collaborator":"Hamani Oumarou",
        "Gender":"male",
        "Affiliation":"Abdou Moumouni University",
        "Country":"Niger",
        "Coordinate location":"13.50136111,2.09852778",
        "URL":"https:\/\/remoboko.hypotheses.org\/tag\/hamani-oumarou"
    },
    {
        "Collaborator":"Hamissou Rhissa Achaffert",
        "Gender":"male",
        "Affiliation":"University of Bayreuth",
        "Country":"Germany",
        "Coordinate location":"49.92885,11.5859",
